# -*- coding: utf-8 -*-
"""final.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nK-MJkHd2E5F7APMvzIWX_j8HAwGGfH
"""

#FINAL
import re

# Listas de palabras
body_shaming = ["gorda", "ballena", "gordo", "esqueleto", "anorexica", "anorexico", "bulto", "obesa", "obeso", "deforme", "mounstro", "narizona", "frentona","asco tu cuerpo"]
discriminacion = ["prieto", "naco", "nazi", "gay", "chinito", "enano", "marimacha", "marica", "manco"]
amenazas = ["no vas a escapar", "te voy a matar", "te hare papilla", "no podras huir", "vas a desaparecer", "te hare la vida imposible", "te voy a castigar", "odiaras haber nacido"]
lenguaje_ofensivo = ["pendejo", "chingadera", "culero", "cabron","mamón", "idiota", "mongolo", "estupido"]
acoso_sexual = ["tócate","sexy", "tetona","desnúdame","culito", "mamacita","papito"]

# Unir todas las listas en una sola lista
todas_las_palabras = body_shaming + discriminacion + amenazas + lenguaje_ofensivo + acoso_sexual

# Diccionario de usuarios
usuarios = {}

def limpiar_texto(texto):
    return re.sub(r'[^a-zA-ZñÑáéíóúÁÉÍÓÚ ]', '', texto).lower()

def censurar(texto):
    texto_censurado = texto
    for palabra in todas_las_palabras:
        patron = r''
        for letra in palabra:
            patron += letra + r'[^a-zA-ZñÑáéíóúÁÉÍÓÚ]*'
        regex = re.compile(patron, re.IGNORECASE)
        texto_censurado = regex.sub('*' * len(palabra), texto_censurado)
    return texto_censurado

print("Sistema de comentarios iniciado...")

while True:
    usuario = input("\nNombre de usuario (o 'salir' para terminar): ")
    if usuario.lower() == "salir":
      print("Sistema cerrado.")
      break

    # Si el usuario no existe, lo agregamos con advertencias=0 y baneado=False
    if usuario not in usuarios:
        usuarios[usuario] = {"advertencias": 0, "baneado": False}

    # Si el usuario ya está baneado, no puede escribir más
    if usuarios[usuario]["baneado"]:
        print(f"{usuario} está baneado y no puede escribir más.")
        continue

    comentario = input("Escribe un comentario: ")
    comentario_limpio = limpiar_texto(comentario)

    if any(re.search(rf'\b{palabra}\b', comentario_limpio, re.IGNORECASE) for palabra in todas_las_palabras):
        usuarios[usuario]["advertencias"] += 1
        advertencia_num = usuarios[usuario]["advertencias"]
        comentario_censurado = censurar(comentario)

        print(f"\nAdvertencia {advertencia_num}/3 para {usuario}:")
        print(f"Comentario censurado: {comentario_censurado}")

        if advertencia_num >= 3:
            usuarios[usuario]["baneado"] = True
            print(f"{usuario} ha sido baneado por exceso de malas palabras.")
    else:
        print("Comentario aceptado.")